workdir: '../..'


rule all:
    input:
        'raw/',
        'download.log'

rule download_from_sciebo:
    output: directory('raw/')
    run:
        import sys
        import os
        sys.path.append(os.path.abspath('../consult_repo'))
        from fsspec.implementations.local import LocalFileSystem

        from src import ScieboDataDownload

        fs_raw = LocalFileSystem()

        if not fs_raw.exists(output, detail=False):
            sciebo_download = ScieboDataDownload()
            sciebo_download.download_raw_reports(destination=str(output))

rule delete_timestamp:
    input: 
        'raw/'
    output: 
        'download.log'
    run:
        import os
        from datetime import datetime
        timestamp_file = input[0]+'/.snakemake_timestamp'

        if os.path.exists(timestamp_file):
            os.remove(timestamp_file)  

        with open(output[0], 'w') as f:
            f.write(f"Data downloaded on: {datetime.now()}")                    
