workdir: '../'

rule download_from_sciebo:
    output: 'raw/'
    run:
        import sys
        import os
        sys.path.append(os.path.abspath('../consult_repo'))
        from fsspec.implementations.local import LocalFileSystem

        from src import ScieboDataDownload


        os.environ['DB_WRITEMODE'] = '1'
        fs_raw = LocalFileSystem()

        if not fs_raw.exists('{output}', detail=False):
            sciebo_download = ScieboDataDownload()
            sciebo_download.download_raw_reports(destination='raw/')
        