workdir: '../..'

rule consolidate_reports:
    input:
        path="raw_data/"
    output:
        path="processed_data/consolidated_report.txt"
    run:
        shell("python scripts/consolidate_reports.py {input.path} {output.path}")

rule write_json:
    input:
        path="processed_data/consolidated_report.txt"
    output:
        path=directory("analysis_data")
    run:
        shell("mkdir {output.path}")
        shell("python scripts/consulting_analysis.py {input.path}")
        shell("mv *.json {output.path}")
