workdir: '../..'

rule consolidate_reports:
    input: 
        directory="raw_data/"
    output: 
        file="processed_data/consolidated_report.txt"
    shell:
        "python scripts/consolidate_reports.py {input.directory} {output.file}"
