name: consulting-reports
channels:
  - defaults
dependencies: 
  - python=3.12
  - pip
  - pip:
      - livereload
      - dvc
      - webdav4
      - fsspec
      - python-docx
      - python-dotenv
      - doit
      - papermill
      - -e ../group_data





