name: consulting-analysis
channels:
  - defaults
dependencies: 
  - python=3.12
  - pip
  - pip:
      - livereload
      - webdav4
      - fsspec
      - python-docx
      - python-dotenv
      - -e ../group_data





