# Use this to set up a virtual environment with all dependencies, except for the python dependencies.
name: ibots-site
channels:
  - defaults
dependencies: 
  - pip
  - python=3.12
  - nodejs
  - pip:
    - -r requirements.txt

  





