name: Publish Website

on: [push]
    

permissions:
  contents: read

jobs:
  deploy:

    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./website

    
    steps:
        - uses: actions/checkout@v4
        
        - name: Setup Micromamba
          uses: mamba-org/setup-micromamba@v1
          with:
            micromamba-version: '1.5.8-0' # any version from https://github.com/mamba-org/micromamba-releases
            environment-file: ./website/environment.yml
            init-shell: powershell
            cache-environment: true
            post-cleanup: 'all'

        - name: Check DVC is available
          run: |
            dvc pull -r dev
