name: Publish Website

on: [push]
    

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./website

    permissions:
      pages: write      # to deploy to Pages
      id-token: write


    steps:
        - uses: actions/checkout@v4
        
        - name: Setup Micromamba
          uses: mamba-org/setup-micromamba@v1
          with:
            micromamba-version: '1.5.8-0' # any version from https://github.com/mamba-org/micromamba-releases
            environment-file: ./website/environment.yml
            init-shell: powershell
            cache-environment: true
            post-cleanup: 'none'

        - name: Get latest Group Database data
          run: |
            cd ../group_data
            dvc remote modify --local dev user ${{ secrets.DB_USERNAME }}
            dvc remote modify --local dev password ${{ secrets.DB_PASSWORD }}
            dvc pull
            cd ../website

        - name: Pull other data dependencies
          run: |
            dvc update data
            dvc pull -r dev

        - name: Run rendering engine
          run: |
            python main.py render

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v4
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./_output

        