name: Publish Website

on: [push]
    

permissions:
  contents: read

jobs:
  deploy:

    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./website

    
    steps:
        - uses: actions/checkout@v4
        
        # - name: Setup Miniconda
        #   uses: conda-incubator/setup-miniconda@v3.0.4
        #   with:
        #     activate-environment: ibots-site
        #     environment-file: ./website/environment.yml  
        
        # - name: Check Conda works
        #   run: |
        #     conda info
        #     conda env list
        
        - name: Setup Micromamba
          uses: mamba-org/setup-micromamba@v1
          with:
            micromamba-version: '1.5.8-0' # any version from https://github.com/mamba-org/micromamba-releases
            environment-file: ./website/environment.yml
            init-shell: powershell
            cache-environment: true
            post-cleanup: 'all'

        - name: Check DVC is available
          run: |
            dvc pull
