name: Publish Website

on: [push]
    

permissions:
  contents: read

jobs:
  deploy:

    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./website

    
    steps:
        - uses: actions/checkout@v4
        
        - name: Setup Micromamba
          uses: mamba-org/setup-micromamba@v1
          with:
            micromamba-version: '1.5.8-0' # any version from https://github.com/mamba-org/micromamba-releases
            environment-file: ./website/environment.yml
            init-shell: powershell
            cache-environment: true
            post-cleanup: 'all'

        - name: Get latest Group Database data
          run: |
            cd ../group_data
            dvc config core.remote dev
            dvc remote modify dev user ${{ secrets.DB_USERNAME }}
            dvc remote modify dev user ${{ secrets.DB_PASSWORD }}
            cd ../website
            dvc update data

        - name: Pull other data dependencies
          run: |
            dvc pull -r dev

        