name: Consulting Report Extraction

on: 
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest
        defaults:
            run:
                working-directory: ./consulting_reports_extraction
        steps:
            - uses: actions/checkout@v4

            - name: Setting Up Python (3.12)
              uses: actions/setup-python@v3
              with:
                  python-version: '3.12'

            - name: Install Package installer
              run: |
                pip install uv
                  
              
            - name: Install Python Libraries
              run: |
                python -m uv pip install -r requirements.txt 

            - name: Get latest Group Database data
              run: |
                cd ../group_data
                dvc remote modify --local dev user ${{ secrets.DB_USERNAME }}
                dvc remote modify --local dev password ${{ secrets.DB_PASSWORD }}
                dvc pull
                cd ../consulting_reports_extraction
      
            - name: Check branch and run script
              env:
                HASH_USR: ${{ secrets.HASH_USR }}
                HASH_PWD: ${{ secrets.HASH_PWD }}
                REPORT_USR: ${{ secrets.REPORT_USR }}
                REPORT_PWD: ${{ secrets.REPORT_PWD }}
              if: github.ref == 'refs/heads/consult_pipeline'
              run: |
                doit download
                doit extract
                doit upload


            
        
                
